apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-dev-inventory
  namespace: openshift-stakater-argocd
  labels:
    stakater.com/tenant: veeru
    stakater.com/env: dev
    stakater.com/kind: dev     
spec:
  destination:
    namespace: veeru-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/apps/01-stakater-nordmart-inventory/01-dev
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true