
stakater-nordmart-review:
  application: 
    namespace:
      enabled: false
    deployment:   
      image:
        repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review
        tag: 0.0.796
