stakater-nordmart-review-ui:
  application:
    route:
       additionalLabels:
          router: default

    deployment:
      image:
        repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review-ui
        tag: 0.0.11
      imagePullSecrets: nexus-docker-config-forked-test
