stakater-nordmart-review-ui:
  application:
    route:
       additionalLabels:
          router: default

    deployment:
      image:
        repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
        tag: 1.0.2
      imagePullSecrets: nexus-docker-config-forked-devtest
