
stakater-nordmart-review:
  application: 
    space:
       enabled: false
    deployment:   
      image:
        repository: nexus-docker-openshift-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review
        tag: 0.0.777

 
