apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-dev-stakater-nordmart-review
  namespace: stakater-argocd
  labels:
    tenant.stakater.com/name: "gabbar" 
    env.stakater.com/name: "dev"
    env.stakater.com/kind: "dev"         
spec:
  destination:
    namespace: gabbar-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/01-stakater-nordmart-review/01-dev
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  project: gabbar-dev 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
