apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-preview-inventory
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: veeru-preview
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/01-stakater-nordmart-inventory/00-preview
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true