apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Space
metadata:
  name: veeru-preview
  labels:
    env.stakater.com/name: 'preview'
    env.stakater.com/kind: 'preview'
    kind: 'pr'
spec:
  tenant: veeru