apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-preview-stakater-nordmart-review
  namespace: stakater-argocd
  labels:
    tenant.stakater.com/name: "gabbar" 
    env.stakater.com/name: "preview"
    env.stakater.com/kind: "preview"     
spec:
  destination:
    namespace: gabbar-preview
    server: 'https://kubernetes.default.svc'
  project: gabbar-preview
  source:
    path: 01-gabbar/01-stakater-nordmart-review/00-preview
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
