pipeline-charts:
  name: stakater-main-pr-v2
  workspaces:
    - name: source
      volumeClaimTemplate:
        accessModes: ReadWriteOnce
        resourcesRequestsStorage: 1Gi
  pipelines:
    finally:
      - taskName: stakater-update-cd-repo-v3
        name: stakater-rollback-cd-repo
        when:
        - input: $(tasks.stakater-e2e-test-v1.status)
          operator: in
          values: [“Failed”]
        params:
        - name: IMAGE_TAG
          value: $(tasks.stakater-update-cd-repo-v3.results.LAST_TAG)
      - taskName: stakater-set-commit-status-v1
        name: set-commit-status-task-result
    tasks:
      - taskName: stakater-set-commit-status-v1
        params:
        - name: state
          value: pending
      - taskName: git-clone
      - taskName: stakater-create-git-tag-v1
      - taskName: stakater-code-linting-v1
      - taskName: stakater-kube-linting-v1
        runAfter:
        - stakater-create-git-tag-v1
      - taskName: stakater-unit-test-v1
        runAfter:
        - stakater-kube-linting-v1
        - stakater-code-linting-v1
      - taskName: stakater-sonarqube-scanner-v1
        runAfter:
          - stakater-unit-test-v1
      - taskName: stakater-buildah-v1
        name: build-and-push
        runAfter:
        - stakater-unit-test-v1
      - taskName: stakater-trivy-scan-v1
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-image-scan
        params:
        - name: image_digest
          value: $(tasks.build-and-push.results.IMAGE_DIGEST)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-image-check
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: rox-deployment-check
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: stakater-checkov-scan-v1
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - taskName: stakater-comment-on-github-pr-v1
        runAfter:
        - stakater-trivy-scan-v1
        - rox-image-scan
        - rox-image-check
        - rox-deployment-check
        - stakater-checkov-scan-v1
      - taskName: stakater-helm-push-v1
      - taskName: stakater-create-environment-v1
      - taskName: stakater-update-cd-repo-v3
      - taskName: stakater-push-main-tag-v1
      - taskName: stakater-app-sync-and-wait-v1
      - taskName: stakater-e2e-test-v1
  triggertemplate:
    serviceAccountName: stakater-tekton-builder
  eventlistener:
    serviceAccountName: stakater-tekton-builder
    triggers:
    - name: stakater-pr-cleaner-v2-pullrequest-merge
      create: false
    - name: pullrequest
      bindings:
      - ref: stakater-pr-v1
    - name: push
      bindings:
      - ref: stakater-main-v1
