stakater-tekton-chart:
  name: stakater-main-pr-v2
  workspaces:
    - name: source
      volumeClaimTemplate:
        accessModes: ReadWriteOnce
        resourcesRequestsStorage: 1Gi
  pipelines:
    finally:
      - taskName: stakater-set-commit-status-v1
        name: set-commit-status-task-result
      - taskName: stakater-notify-slack-v1
        name: notify-slack
        params:
        - name: namespace
        - name: author
        - name: gitrevision
        - name: repo
          value: $(params.repoName)
        - name: gitrepositoryurl
        - name: tekton-base-url
        - name: prnumber
    tasks:
      - defaultTaskName: stakater-set-commit-status-v1
        params:
        - name: state
          value: pending
      - defaultTaskName: git-clone
      - defaultTaskName: stakater-create-git-tag-v1
      - defaultTaskName: stakater-code-linting-v1
      - defaultTaskName: stakater-kube-linting-v1
        params:
        - name: namespace
          value: $(context.pipelineRun.namespace)
        runAfter:
        - stakater-create-git-tag-v1
      - defaultTaskName: stakater-unit-test-v1
        runAfter:
        - stakater-kube-linting-v1
        - stakater-code-linting-v1
      - defaultTaskName: stakater-sonarqube-scanner-v1
        runAfter:
          - stakater-unit-test-v1
      - defaultTaskName: stakater-build-image-flag-v1
        runAfter:
          - stakater-unit-test-v1
      - defaultTaskName: stakater-buildah-v1
        name: build-and-push
        runAfter:
          - stakater-build-image-flag-v1
        params:
          - name: BUILD_IMAGE
            value: $(tasks.stakater-build-image-flag-v1.results.build-image)
      - defaultTaskName: stakater-trivy-scan-v1
        params:
          - name: BUILD_IMAGE
            value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - defaultTaskName: rox-image-scan
        params:
        - name: image_digest
          value: $(tasks.build-and-push.results.IMAGE_DIGEST)
        - name: BUILD_IMAGE
          value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - defaultTaskName: rox-image-check
        params:
          - name: BUILD_IMAGE
            value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - defaultTaskName: rox-deployment-check
        params:
          - name: BUILD_IMAGE
            value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - defaultTaskName: stakater-checkov-scan-v1
        params:
          - name: BUILD_IMAGE
            value: $(tasks.stakater-build-image-flag-v1.results.build-image)
        runAfter:
        - build-and-push
        - stakater-sonarqube-scanner-v1
      - defaultTaskName: stakater-comment-on-github-pr-v1
        runAfter:
        - stakater-trivy-scan-v1
        - rox-image-scan
        - rox-image-check
        - stakater-checkov-scan-v1
      - defaultTaskName: stakater-helm-push-v1
      - defaultTaskName: stakater-create-environment-v1
      - defaultTaskName: stakater-update-cd-repo-v3
      - defaultTaskName: stakater-push-main-tag-v1
      - defaultTaskName: stakater-app-sync-and-wait-v1
        params:
        - name: timeout
          value: "300"
  triggertemplate:
    serviceAccountName: stakater-tekton-builder
    pipelineRunNamePrefix: $(tt.params.repoName)-$(tt.params.prnumberBranch)
  eventlistener:
    serviceAccountName: stakater-tekton-builder
    triggers:
    - name: stakater-pr-cleaner-v2-pullrequest-merge
      create: false
    - name: pullrequest-create
      create: true
      bindings:
      - ref: stakater-pr-v1
      - name: oldcommit
        value: $(body.pull_request.base.sha)
      - name: newcommit
        value: $(body.pull_request.head.sha)
    - name: pullrequest-synchronize
      create: true
      bindings:
        - ref: stakater-pr-v1
        - name: oldcommit
          value: $(body.before)
        - name: newcommit
          value: $(body.after)
    - name: push
      create: true
      bindings:
        - ref: stakater-main-v1
        - name: oldcommit
          value: $(body.before)
        - name: newcommit
          value: $(body.after)
  rbac:
    enabled: false
  serviceAccount:
    name: stakater-tekton-builder
    create: false
