stakater-nordmart-inventory:
     application:
         space:
             enabled: false
         deployment:
             image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
              tag: 0.0.23