stakater-nordmart-inventory:
  application:
    deployment:
      image:
        repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
        tag: 1.0.0
